### PR TITLE
Added config option for canImportResource default value

### PR DESCRIPTION
**Pull request by TheRealMkadmi**
In a lot of cases, we'd have a large number of Resources with just a few of them "bulk importable". It's cumbersome to have to add `$canImportResource = false` in each request.

### CODE REVIEW

**Comment by simonhamp** [comment]
I think your issue is valid, but there's a lot of 'extra' stuff in this PR that doesn't appear to be related to solving that problem.

Please can you strip this back/split it up so that each set of changes is focussed on just one issue?

**Comment by chihabhajji** [comment]
LGTM!

**Comment by MoetazBrayek** [comment]
LGTM!

**Comment by simonhamp** [comment]
@chihabhajji @MoetazBrayek that's not going to get this merged I'm afraid... needs more work

**Pull request closed without merging**
